# Generated by Django 3.2.8 on 2021-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default=None, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
