# Generated by Django 3.2.8 on 2021-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20211031_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courserelations',
            unique_together={('prerequisite', 'post_requisite')},
        ),
    ]
