# Generated by Django 3.2.8 on 2021-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20211102_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
