# Generated by Django 3.2.8 on 2022-01-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserelations',
            name='from_eduwiki',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='courserelations',
            name='post_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courserelations',
            name='pre_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
