# Generated by Django 3.2.8 on 2022-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20220131_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
