# Generated by Django 3.2.8 on 2022-02-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20220131_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='courserelations',
            name='from_eduwiki',
        ),
        migrations.RemoveField(
            model_name='courserelations',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='courserelations',
            name='pre_name',
        ),
    ]
