# Generated by Django 3.2.8 on 2022-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_alter_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='from_eduwiki',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
