# Generated by Django 3.2.8 on 2022-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20220201_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
