# Generated by Django 3.2.8 on 2022-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='courserelations',
            name='from_eduwiki',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='courserelations',
            name='post_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courserelations',
            name='pre_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
