# Generated by Django 3.2.8 on 2022-02-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_course_from_eduwiki'),
        ('tree', '0010_auto_20220203_0628'),
    ]

    operations = [
    ]
