# Generated by Django 3.2.8 on 2022-03-29 08:24

from django.db import migrations, models

from tree.models import Category


def add_categories(apps, schema_editor):
    Category.objects.create(course_ids='CSE1', name='Computer Science, Programming', color='Lavender')
    Category.objects.create(course_ids='CSE2', name='Maths', color='LightPink')
    Category.objects.create(course_ids='CSE3', name='Artificial Intelligence', color='NavajoWhite')
    Category.objects.create(course_ids='CSE4', name='Hardware and Robotics', color='Khaki')
    Category.objects.create(course_ids='CSE5', name='Security and Networks', color='PaleGreen')
    Category.objects.create(course_ids='CSE6', name='Business and analytics', color='DarkSalmon')
    Category.objects.create(course_ids='CSE7', name='Research', color='PaleTurquoise')
    Category.objects.create(course_ids='CSE8', name='Software Engineering', color='Silver')
    Category.objects.create(course_ids='HSS1', name='Pedagogy', color='MistyRose')
    Category.objects.create(course_ids='HSS2', name='Languages and literature', color='LightCyan')
    Category.objects.create(course_ids='HSS3', name='Business management', color='LightSteelBlue')
    Category.objects.create(course_ids='HSS4', name='Psychology and negotiation', color='Wheat')
    Category.objects.create(course_ids='HSS5', name='The science', color='LemonChiffon')


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_merge_20220222_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ids', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RunPython(add_categories)
    ]
