# Generated by Django 3.2.8 on 2022-04-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserelations',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
